#!/usr/bin/env python3
"""Generate all DrawIO XML files for the green electricity-hydrogen-ammonia park paper."""
import os

OUT_DIR = "figures"

def write_file(filename, content):
    path = os.path.join(OUT_DIR, filename)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Created: {path} ({len(content)} bytes)")

def q2_flow():
    xml = '<mxfile host="draw.io"><diagram name="Q2" id="fq2"><mxGraphModel dx="900" dy="750" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="900" pageHeight="750" background="none" math="0" shadow="0"><root><mxCell id="0"/><mxCell id="1" parent="0"/>'
    xml += '<mxCell id="n1" value="&lt;b&gt;设定产能参数&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;产能72吨/日，按9吨递减至36吨&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0F4FA;strokeColor=#7B9FC0;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="220" y="15" width="280" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e1" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="57" as="sourcePoint"/><mxPoint x="360" y="80" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n2" value="&lt;b&gt;遍历每种产量水平&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;72, 63, 54, 45, 36 吨/日&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#9A8AB0;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="220" y="80" width="280" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e2" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="122" as="sourcePoint"/><mxPoint x="360" y="145" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n3" value="&lt;b&gt;枚举开停机组合&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;电氢氨装置只有全额开机/停机两种状态&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#7AAA7A;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="180" y="145" width="360" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e3" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="187" as="sourcePoint"/><mxPoint x="360" y="210" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n4" value="&lt;b&gt;计算各时段购售电费用&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;分时电价 × 购电量 - 上网电价 × 售电量&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0F4FA;strokeColor=#7B9FC0;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="180" y="210" width="360" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e4" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="252" as="sourcePoint"/><mxPoint x="360" y="275" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n5" value="&lt;b&gt;找最低成本时段&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;选择吨氨成本最低的开机时段组合&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#7AAA7A;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="200" y="275" width="320" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e5" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="317" as="sourcePoint"/><mxPoint x="360" y="340" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n6" value="&lt;b&gt;绿电指标校验&lt;/b&gt;" style="rhombus;whiteSpace=wrap;html=1;fillColor=#F5F0E8;strokeColor=#B0A080;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="300" y="340" width="120" height="70" as="geometry"/></mxCell>'
    xml += '<mxCell id="e6y" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#7AAA7A;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="410" as="sourcePoint"/><mxPoint x="360" y="435" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="lb6y" value="&lt;font style=&quot;font-size:10px;color:#7AAA7A;&quot;&gt;&lt;b&gt;合格&lt;/b&gt;&lt;/font&gt;" style="text;html=1;align=center;verticalAlign=middle;whiteSpace=wrap;strokeColor=none;fillColor=none;" vertex="1" parent="1"><mxGeometry x="365" y="415" width="40" height="18" as="geometry"/></mxCell>'
    xml += '<mxCell id="e6n" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#B08080;endArrow=block;endFill=1;exitX=1;exitY=0.5;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="420" y="375" as="sourcePoint"/><mxPoint x="560" y="435" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="lb6n" value="&lt;font style=&quot;font-size:10px;color:#B08080;&quot;&gt;&lt;b&gt;不合格&lt;/b&gt;&lt;/font&gt;" style="text;html=1;align=center;verticalAlign=middle;whiteSpace=wrap;strokeColor=none;fillColor=none;" vertex="1" parent="1"><mxGeometry x="440" y="360" width="50" height="18" as="geometry"/></mxCell>'
    xml += '<mxCell id="n7" value="&lt;b&gt;记录最优方案&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;开机时段 + 吨氨成本 + 绿电指标&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#FFFFFF;strokeColor=#7AAA7A;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="220" y="435" width="280" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="n7b" value="&lt;b&gt;分析不合格原因&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;购电过多/售电过少&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F5EDED;strokeColor=#B08080;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="480" y="435" width="160" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e7" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="477" as="sourcePoint"/><mxPoint x="360" y="500" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n8" value="&lt;b&gt;24场景统计分析&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;全满足/部分满足/全不满足 + 全年吨氨成本&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0F4FA;strokeColor=#7B9FC0;strokeWidth=1.5;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="170" y="500" width="380" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="e8" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#999999;endArrow=block;endFill=1;exitX=0.5;exitY=1;entryX=0.5;entryY=0;"><mxGeometry relative="1" as="geometry"><mxPoint x="360" y="542" as="sourcePoint"/><mxPoint x="360" y="565" as="targetPoint"/></mxGeometry></mxCell>'
    xml += '<mxCell id="n9" value="&lt;b&gt;输出结果&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;最优产量 + 全年成本分布曲线 + 指标统计&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#E8F0E8;strokeColor=#5A8A5A;strokeWidth=2;fontSize=11;fontStyle=1;" vertex="1" parent="1"><mxGeometry x="190" y="565" width="340" height="42" as="geometry"/></mxCell>'
    xml += '<mxCell id="tools" value="&lt;b&gt;工具与方法&lt;/b&gt;&lt;br&gt;&lt;font style=&quot;font-size:9px;color:#888;&quot;&gt;Python 枚举搜索&lt;br&gt;分时电价计算&lt;br&gt;24场景统计&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F0ECF5;strokeColor=#C8BCD8;strokeWidth=1.5;fontSize=10;fontStyle=1;verticalAlign=top;spacingTop=2;" vertex="1" parent="1"><mxGeometry x="620" y="200" width="140" height="90" as="geometry"/></mxCell>'
    # Loop-back arrow from n7b to n3
    xml += '<mxCell id="eloop" edge="1" parent="1" style="rounded=1;html=1;strokeWidth=1.5;strokeColor=#B08080;endArrow=block;endFill=1;dashed=1;dashPattern=4 4;exitX=1;exitY=0.5;entryX=1;entryY=0.5;"><mxGeometry relative="1" as="geometry"><mxPoint x="640" y="456" as="sourcePoint"/><mxPoint x="540" y="166" as="targetPoint"/><Array as="points"><mxPoint x="680" y="456"/><mxPoint x="680" y="166"/></Array></mxGeometry></mxCell>'
    xml += '</root></mxGraphModel></diagram></mxfile>'
    write_file("fig_flow_q2.drawio", xml)

# PLACEHOLDER_Q3Q4
if __name__ == "__main__":
    q2_flow()
